name: pre-commit-simple

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: HatsuneMiku3939/direnv-action@v1
      - run: |
          pip install -r requirements/dev.txt
          pre-commit run -a
